### ISSUE TITLE
No interactive authentication prompt

### ISSUE THREAD

**Issue by bpoldrack** [psychoinformatics-de/knowledge-base#10]
Origin: https://github.com/datalad/datalad/issues/7365

TODO (not necessarily to be performed in this order)
- [x] Inform OP/Add reference to this issue at origin
- [ ] Clarifying Qs asked or not needed
- [ ] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by bpoldrack** [comment]
I'm not sure to what extend it is useful to have a somewhat duplicate summary of the state of the issue here. But since we are trying to track what is done and needs doing, it may be good. So, here it is:


User reported the datalad special remote not asking for a LORIS token, but hanging during `get` instead. Not reproduced by @adswa and @bpoldrack with the same dataset.
Disabling keyring by setting `export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring` makes the prompt appear, suggesting that some keyring backend (or combination thereof) does not quite work as expected. Running `git annex get` with `DATALAD_LOG_LEVEL=9` and `DATALAD_LOG_TRACEBACK=collide` reports the following backends loaded for the user:

```
[DEBUG] …>http:582,175>credentials:376,107,108,119>keyring_:78,46  Importing keyring
[INFO] …>keyring_:78,47><frozen importlib._bootstrap>:991,975,671><frozen importlib._bootstrap_external>:848><frozen importlib._bootstrap>:219>keyring.__init__:3><frozen importlib._bootstrap>:991,975,671><frozen importlib._bootstrap_external>:848><frozen importlib._bootstrap>:219>core:189,93>util.__init__:21>backend:207,193  Loading KWallet
[INFO] …>backend:207,193  Loading SecretService
[INFO] …>backend:207,193  Loading Windows
[INFO] …>backend:207,193  Loading chainer
[INFO] …>backend:207,193  Loading macOS
[INFO] …>backend:207,193  Loading Gnome
[INFO] …>backend:207,193  Loading Google
[INFO] …>backend:207,193  Loading Windows (alt)
[INFO] …>backend:207,193  Loading file
[INFO] …>backend:207,193  Loading keyczar
[INFO] …>backend:207,193  Loading multi
[INFO] …>backend:207,193  Loading pyfs
```

`datalad wtf` reports these as active backends:

- SecretService Keyring
- EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at ~/.local/share/python_keyring/crypted_pass.cfg
- PlaintextKeyring with no encyption v.1.0 at ~/.local/share/python_keyring/keyring_pass.cfg

Currently not clear, what exactly is causing the issue.

**Comment by mih** [comment]
OP reports that the following workaround helped them, and that they were able to move on and consider the issue resolved:

```
It turns out this issue has something to do with the keyring, as @bpoldrack noticed. Not sure exactly what or how but disabling the keyring using export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring gives me a user prompt for credentials.
```

We should write this up as a small KBI, suggesting what could be tried if no expected prompts appear.
