### ISSUE TITLE
How to set the clone priorities

### ISSUE THREAD

**Issue by loj** [psychoinformatics-de/knowledge-base#109]
Origin: https://neurostars.org/t/how-to-set-clone-locations-to-local-only-on-hpc/26370

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [ ] Inform OP about resolution

I posted a response on neurostars, and believe the chapter [1.5.2 Clone candidate priority](https://handbook.datalad.org/en/latest/beyond_basics/101-148-clonepriority.html#clone-candidate-priority) of the DataLad Handbook covers the situation.

Will wait for confirmation from OP.

**Comment by mslw** [comment]
The OP seems to have found an error in DataLad docs - I responded in the thread with what seems to be the correct parameter name, and opened https://github.com/datalad/datalad/issues/7458

**Comment by loj** [comment]
Thanks @mslw for figuring this out! The OP confirmed that your suggestion worked for them.
