### ISSUE TITLE
How to disable an invalid special remote?

### ISSUE THREAD

**Issue by bpoldrack** [psychoinformatics-de/knowledge-base#11]
Origin: Datalad Office Hour

A user used to have RIA store with the respective ORA special remote (autoenabled). Removed the store, since it was no longer needed, leading to every subsequent `datalad clone` of the dataset issuing a warning about not being able to find the store. The user was told to declare the special remote dead and push that change in order to not have `datalad get` consider this source anymore, but a `git annex enableremote NAME autoenable=false` to not have `datalad`/`git-annex` try to autoenable with each clone fails, since `enableremote` does actually try to enable and therefore fails the same way (also not storing the changed config).
There is no actual resolution at the moment. It may be an option to change the special remote implementation to not try and actually connect during `enableremote` ( == `INITREMOTE` in the special remote protocol) in order to allow a reconfiguration via this command to apply regardless.
It's probably also worth pointing out to git-annex, that something like a `git annex configremote` or alike could be desirable.

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by mih** [comment]
Given the assessment by @bpoldrack I created a reproducer and filed an upstream issue https://git-annex.branchable.com/bugs/Disabling_remote_auto-enabling_not_possible

**Comment by mih** [comment]
https://github.com/psychoinformatics-de/knowledge-base/pull/22 that brought https://knowledge-base.psychoinformatics.de/kbi/0006 has also identified a workaround, and git-annex will likely bring the `configremote` solution mentioned above.

**Comment by mih** [comment]
I posted an update on this issue in the office hour chat:

```
Some time back we discussed an issue in the office hour where it was impossible to disable the auto-enabling of a special remote that pointed to a RIA store which no longer existed. We investigated this problem and identified that it also applies to other scenarios.

This issue is likely to be addressed by git-annex directly. See https://git-annex.branchable.com/bugs/Disabling\_remote\_auto-enabling\_not\_possible for updates.

In the meantime, more information and a possible workaround is available from https://knowledge-base.psychoinformatics.de/kbi/0006
```
