### ISSUE TITLE
How to overwrite files without having to unlock

### ISSUE THREAD

**Issue by adswa** [psychoinformatics-de/knowledge-base#16]
Origin: A user message in the DataLad Office hour chat April 12th, 5pm CEST

A user described their workflow as follows: They regularly do interactive computations with jupyter notebooks on intermediate results. The computations change certain annexed results in their dataset hierarchy. The original question was if there was a better way to circumvent the constant "permission denied" errors than manually unlocking the files every time.

Several solutions were offered and discussed:
- delete the (previous version of) the file, write it anew and save
- unlocking the files permanently via ``git annex config --set annex.addunlocked 'include=<pattern>'``
- wrapping the command into ``datalad run``

Furthermore it turned out, that the user was trying to write their results from within a jupyter notebook.
While discussing the `datalad run` approach in detail (wrapping the notebook execution) there were additional confusions encountered:
- `datalad run` was executed from within a subdataset, while the output file in question was part of the superdataset
- `run` was initially executed via python API from within the notebook and a python function passed to it as the command to execute

Potentially also noteworthy - with respect to writing a KBI - is that the user was using python but was unaware of `Path` or `unlink` (and its meaning). Just as a hint to what can be assumed in what context.

Ultimately, user got the `datalad run` wrapping the notebook invocation to work as well as the approach to `unlink` and `save` directly via python API.

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [x] Inform OP about resolution

**Comment by loj** [comment]
I think this can be closed. I believe [KBI0003](https://knowledge-base.psychoinformatics.de/kbi/0003/index.html) now covers this topic well. If that's not the case, please feel free to reopen this issue.

Thanks @adswa!
