### ISSUE TITLE
How to remove the annex part of a dataset using git annex uninit

### ISSUE THREAD

**Issue by adswa** [psychoinformatics-de/knowledge-base#23]
Origin: ~Office hour~ DataLad chat, April 17th

Users asked whether git-annex uninit would be the go to command to remove the annex branch from a datalad dataset that would suffice to be a git repository. 
The user followed up that the dataset in question had a sibling, and that a datalad push would reinstate the git-annex branch that the uninit had removed.

see also: https://github.com/datalad-handbook/book/issues/939

TODO (not necessarily to be performed in this order)
- [x] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [x] Inform OP about resolution

**Comment by mslw** [comment]
Relevant link: [git annex uninit](https://git-annex.branchable.com/git-annex-uninit/)

**Comment by christian-monch** [comment]
Added a detailed description here: https://github.com/datalad-handbook/book/issues/939#issuecomment-1516362187

**Comment by adswa** [comment]
whoops, I think this got closed by accident? Please re-close if you disagree :smile:
