### ISSUE TITLE
Installing DataLad dependencies in Google Colab

### ISSUE THREAD

**Issue by adswa** [psychoinformatics-de/knowledge-base#42]
Origin: Stackoverflow: https://stackoverflow.com/questions/74774823/google-colab-git-annex-update-issue

A user tried to install datalad and its dependencies on Google Colab, but an apt-get-based installation of git-annex resulted in a vastly outdated git-annex version 6.20180227.

I recommended using the datalad-installer or a conda-based installation as shown in the datalad handbook.
I think a KBI on installing datalad in google collab is a useful addition to the knowledge base.

- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by adswa** [comment]
A potential resource for a prospective KBI: @mslw shared https://stackoverflow.com/questions/55253498/how-do-i-install-a-library-permanently-in-colab/55253499 in the labchat, which details how to permanently install libraries in Google Collab

**Comment by jsheunis** [comment]
I made a colab notebook that details the process of installing datalad and dependencies via conda in colab (however not permanently): https://colab.research.google.com/drive/1SR-I-BDxQ5bHUKjABYI1Uu4HFlfDjOYE?usp=sharing
