### ISSUE TITLE
What is the preferred strategy for creating and updating an archive.7z in a RIA store?

### ISSUE THREAD

**Issue by christian-monch** [psychoinformatics-de/knowledge-base#47]
Origin: [incf NeuroStars (Software support, datalad)](https://neurostars.org/t/what-is-the-preferred-strategy-for-creating-and-updating-an-archive-7z-in-a-ria-store/25683) on 2023-04-26

TODO (not necessarily to be performed in this order)
- [x] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [x] Inform OP about resolution

**Comment by christian-monch** [comment]
Posted a recommendation here: https://neurostars.org/t/what-is-the-preferred-strategy-for-creating-and-updating-an-archive-7z-in-a-ria-store/25683/2?u=cmo

I would appreciate if some of you would take a look at it.

The gist is:

Do not use `export-archive-ora` unless you are the only one using the RIA-store and know what you do, instead, perform the following steps:

1. Lock the RIA-store for “maintenance”
2. If you can afford it space-wise, create a backup copy of `archive.7z`. That can be in a temporary space.
3. Update `archive.7z` with the content of `<dataset-uuid[3:]>/annex/objects`, using the update-flag, i.e. `u`, when modifying the archive.
4. Check that the current content of `<dataset-uuid[3:]>/annex/objects` is contained in the archive. If not use, the backup to recover, adjust and try again.
5. Remove all content in `<dataset-uuid[3:]>/annex/objects`.
6. Unlock the RIA-store.
7. Delete the backup copy of the archive

**Comment by loj** [comment]
> I keep this issue open for now because I would appreciate it if some of you would take a look at it.

I read through your recommendation, and I think it sounds like a good approach. It is similar to a workflow @mih created (see below) when we needed to reduce the number of inodes used by an existing RIA store. I think it would be worth creating a KBI covering this.

Clean-up and archive a datastore to reduce inodes:
```bash
find dsstore -mindepth 2 -maxdepth 2 -type d | xargs -n1 bash cleanup.sh
```

``` bash
❱ cat cleanup.sh
#!/bin/bash
set -e -u

echo "Processing $1"

cd $1
ds_path="$(readlink -f .)"

test -f config || ( echo "not a repository: $1" && exit 1 )

rm -f info/exclude
rm -f hooks/*
test -d info && rmdir --ignore-fail-on-non-empty info
test -d hooks && rmdir --ignore-fail-on-non-empty hooks
rm -rf annex/journal
rm -f annex/index
rm -f annex/index.lck
rm -f annex/journal.lck
rm -f annex/othertmp.lck
test -d annex/othertmp && rmdir annex/othertmp
test -d ora-remote-*/transfer && rmdir --ignore-fail-on-non-empty ora-remote-*/transfer
test -d ora-remote-* && rmdir --ignore-fail-on-non-empty ora-remote-*

# uncompressed archive by default
sevenzopts=${HP_ZIPOPTS:--mx0}

objpath="$(readlink -f annex/objects)"
archivepath="$(readlink -f archives)"

if [ ! -d "$objpath" ]; then
        >&2 echo "No annex objects. Done."
        exit 0
fi

if [ ! -d "$archivepath" ]; then
        mkdir -p "$archivepath"
        # only chown when freshly created to not destroy potential
        # custom permission setup
        # whoever owns the object store, owns the archives
        chown -R --reference "$objpath" "$archivepath"
fi

mv "$objpath" "$objpath"_
objpath="$objpath"_

cd "$objpath"
# always update, also works from scratch
7z u "$archivepath/archive.7z" . $sevenzopts
chown -R --reference "$objpath" "$archivepath"/archive.7z
cd -

rm -rf "$objpath"
rmdir --ignore-fail-on-non-empty "$ds_path/annex"
```
