### ISSUE TITLE
Is there a way to drop only the files pushed in the last push but keep others?

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/knowledge-base#51]
Origin: DataLad matrix chatroom 2023-05-03

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [x] Inform OP about resolution

**Communication with user:**

> Is there a way to drop only the files pushed in the last push but keep others?

Can you maybe give a bit more context for clarification? When you say "drop" do you mean datalad drop files after they were retrieved by `datalad get`? Since a `datalad push`, and a corresponding `datalad update`, would update the git repository (via fetch / merge / or whichever method) but would not automatically retrieve the new/updated content.

> I mean `datalad drop` after a `datalad push` (idea is to drop big files added to this commit, but keep big files from other commits. (use case is drop new data files, but keep some pdf files that were previously added).

ah OK, so: user adds local data to a dataset annex -> `datalad save` -> `datalad push` -> `datalad drop` all files that were added in the last commit (or last X commits?).

You should be able to get the names of changed files via a git diff given the commit hashes. For example:
```
git diff --name-only <commit_before_changes>..<commit_after_changes>
```
and then drop those individually.

Alternatively, before the save, `datalad status` can also give you a list of changed files.

**Comment by christian-monch** [comment]
Sufficiently answered by @jsheunis in DataLad matrix chatroom 2023-05-03

**Comment by adswa** [comment]
I personally think this question deserves a persistent write-up in a KBI; the information is lost if its in this issue and the chat room only. Thus, I'm reopening this

**Comment by jcolomb** [comment]
see https://github.com/tonic-team/synchronisation_scripts/pull/17/files for an implementation in python script (not tested yet).
