### ISSUE TITLE
Update knowledge base HTML theme

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/knowledge-base#53]
I don't know about other people, but the current `alabaster` theme is completely uninviting for me, especially for a knowledge base. The themes that ship with sphinx (https://www.sphinx-doc.org/en/master/usage/theming.html#builtin-themes) all look a bit old, too.

Here are some more recent examples: https://sphinx-themes.org/

I particularly like these ones for the knowledge base:
- https://sphinx-themes.org/sample-sites/sphinx-book-theme/
- https://sphinx-themes.org/sample-sites/furo/
- https://sphinx-themes.org/sample-sites/piccolo-theme/
- https://sphinx-themes.org/sample-sites/sphinx-press-theme/

Any comments?

**Comment by adswa** [comment]
book-theme looks nice!

**Comment by jsheunis** [comment]
I like it too 👍 


I tried the following locally in a virtual environment:

1. Install sphinx from git: `pip install git+https://github.com/sphinx-doc/sphinx.git@v6.2.1` (I saw a notification that the book theme is not compatible with sphinx 7.x.x yet.)
2. Install the book theme: `pip install sphinx-book-theme`
3. add the theme to `conf.py`:  `html_theme = 'alabaster'`
4. run `make html`

But I get an error (which is absent if the theme is `alabaster`):

```
Running Sphinx v6.2.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 13 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
reading sources...
looking for now-outdated files... none found
preparing documents... done
writing output... [100%] kbi/0014/index
generating indices... genindex failed

Theme error:
An error happened in rendering the page genindex.
Reason: KeyError('genindex')
make: *** [html] Error 2
```

I cannot find any useful information about this error online. Can any sphinx experts shed light on this? And can someone try this on their own system to see if the error reproduces?

**Comment by adswa** [comment]
The reason is 73a808f, which added the index to the front page for better discoverability. If you revert this, it should work. This is how it looks like: 
![image](https://user-images.githubusercontent.com/29738718/236124898-d4ae04b5-0e29-4098-9eeb-9394d9aae0d5.png)


Here's the diff

```diff
diff --git a/conf.py b/conf.py
index 3e5b84d..05df1b1 100644
--- a/conf.py
+++ b/conf.py
@@ -23,5 +23,5 @@ exclude_patterns = []
 # -- Options for HTML output -------------------------------------------------
 # https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
 
-html_theme = 'alabaster'
+html_theme = 'sphinx_book_theme'
 html_static_path = ['_static']
diff --git a/index.rst b/index.rst
index 4443c47..aa74c63 100644
--- a/index.rst
+++ b/index.rst
@@ -12,9 +12,3 @@ the topic :ref:`index <genindex>`, or by browsing the list below.
    kbi/*/index
 
 
-.. toctree::
-   :glob:
-   :maxdepth: 1
-   :caption: Index overview
-
-   genindex

```

**Comment by christian-monch** [comment]
My preference would be:

1. piccolo
2. book

To my piccolo looks a little more solid. I think it also looks more structured, in the sense that different semantic blocks are better separated.

**Comment by mih** [comment]
My 2ct: I do not care much about the specific style. What I do care about is the minimization of everything that is not focused on the content. If the selection of any particular theme implies problems on sphinx upgrades, I am in favor of another them. If we cannot use standard sphinx features, because a particular theme doesn't like them, I am in favor of another theme. IOW "form follows function" ;-)

**Comment by jsheunis** [comment]
For easy comparison

### Furo

https://user-images.githubusercontent.com/10141237/236404231-feb2bc2e-2140-45d2-8db5-d814e4f0f2c1.mp4

### Piccolo

https://user-images.githubusercontent.com/10141237/236404349-d1c1f899-f19b-459b-9fe1-e16e3670bb4d.mp4

### Book

(without index)

https://user-images.githubusercontent.com/10141237/236404462-b15d5004-259d-48f2-b4b9-3171f58f4e58.mp4

After considering @mslw's analysis, I vote for Furo.
