### ISSUE TITLE
push to gin error: verification of content failed

### ISSUE THREAD

**Issue by loj** [psychoinformatics-de/knowledge-base#56]
Origin: DataLad Office Hours matrix chatroom 2023-05-05

User reports that pushing to gin (`datalad push --to gin --force all`) results in the error `verification of content failed`

![image](https://user-images.githubusercontent.com/15157717/236426113-2e2c446f-8696-480a-99ca-b66818586986.png)

Details on user's situation:
- pushing over `ssh` to a  private gin repo
- using `datalad 0.18.3` and `git-annex version: 10.20221212`

TODO (not necessarily to be performed in this order)
- [x] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [ ] Nature of the issue is understood
- [ ] Inform OP about resolution

A similar error was reported in #27. It's possible running `git annex fsck` might help solve the problem.

Also related https://git-annex.branchable.com/forum/Should_transfer_to_a_special_remote_verify_source_content__63__/

**Comment by mih** [comment]
It is unclear what is happening here. There has been no further update by OP. I am inclined to close this as a duplicate of #27

**Comment by loj** [comment]
There's been no further updates by OP. I will close this for now, and it can be re-opened if we come across similar reports or get new info from OP.
