### ISSUE TITLE
How to create a new subdataset out of contents that were previously saved in a (to-be-parent) dataset

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/knowledge-base#63]
Origin: DataLad office hour matrix chat, 2023-05-09

Question (paraphrased): how to create a new subdataset out of contents that were previously saved in a (to-be-parent) dataset

Proposed answer (paraphrased from chat comments): for a simple case where contents were committed by accident (and have no history to speak of), a combination of `git annex unannex`, `git reset --mixed`, `datalad create --force` and possibly a cleanup of git annex objects can be sufficient. In general, what methods need to be used depends on why the chang is made. Does one care about the history of the files, or is a "fresh start" sufficient? Does the subdataset have to be located within, or can a copy outside to-be-parent dataset can be made? etc.

The following links were shared for additional information:

- https://knowledge-base.psychoinformatics.de/kbi/0013/index.html
- https://handbook.datalad.org/en/latest/basics/101-136-filesystem.html#moving-files-across-dataset-boundaries
- https://handbook.datalad.org/en/latest/basics/101-136-filesystem.html#copying-files-across-dataset-boundaries

The question is simple if asked in the context of an accidental save, and very complex to answer in general. Given that  we already have materials that address the answer from several angles (though perhaps leaning towards more complex scenarios?), I will close the issue as completed without requiring a KBI.

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by christian-monch** [comment]
> [...] I read all the resources we linked to correctly, none of them fully addresses this particular use case?

I guess the question for a support-ticket would be whether the support case was solved. I would say, it was. So I am closing this again. @jsheunis , a KBI might be a good idea, I created an extra issue for that: https://github.com/psychoinformatics-de/knowledge-base/issues/68
