### ISSUE TITLE
Removing a specific commit and related data from history, while keeping others

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/knowledge-base#65]
Origin: Datalad Office Hour chat; 2023-05-10

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [x] Inform OP about resolution

User:

> Hi, this is a dataset that Im working with and commit X is a commit associated with about 100GB of new data. I dont need them anymore, and I dont want to have them on my gin repo. so How can I git reset hard only that specific commit without loosing the other Y and Z commits?

Psyinf: 

> If I understand the challenge correctly, I think you can do a git rebase interactive, and then drop the specific commit that you are not interested in, while keeping the others.
> You would have to rebase to the commit that precedes the one you want to drop, in your case X: `git rebase -i <full commit sha>`. this will open an editable list of commits (with help info), and next to the one you want to remove you write drop (instead of the default pick), and leave the other commits unchanged. Then save and exit the interactive process. However, I am not exactly sure what a git rebase does to annexed data.
> This write-up seems relevant wrt annexed files: https://handbook.datalad.org/en/0.17/basics/101-137-history.html#untracking-accidentally-saved-contents-stored-in-git-annex

User:
> Ah ok. Do you know if a git reset hard deletes annexed data? or affects them somehow ...

Psyinf:
> I am pretty sure it doesn't. This part from the handbook chapter I linked is relevant:
> > The previous git reset undid the tracking of text files. However, those files are stored in Git, and thus their content is also stored in Git. Files that are annexed, however, have their content stored in git-annex, and not the file itself is stored in the history, but a symlink pointing to the location of the file content in the dataset’s annex. This has consequences for a git reset command: Reverting a save of a file that is annexed would revert the save of the symlink into Git, but it will not revert the annexing of the file. Thus, what will be left in the dataset is an untracked symlink.

Psyinf:

> Rebasing does nothing to git-annex (or data in an annex). This would and will need a git annex unused run. At that point git annex detects that some keys or not longer referenced in any branch's HEAD commits. It will present them, and a following dropunused can drop them
> That being said: not every presently "unused" key is from that single commit
> If you have other historical data that is also now longer references, but still useful, because you change history more than once, or you switch to older states -- BE CAREFUL!
> One useful approach is to have a branch or tag on everything that you care about -- git annex unused would then consider them necessary.
> git annex unused is quite powerful, I recommend studying the help for it

**Comment by christian-monch** [comment]
OP has been informed about the options that we are aware of. A PR for KBI entry 0017 has been created
