### ISSUE TITLE
`containers-run` leaves absolute path to container in the commit message

### ISSUE THREAD

**Issue by christian-monch** [psychoinformatics-de/knowledge-base#67]
OP asks:
> after using datalad containers-run, the cmd in the commit message includes the absolute path to the container, even in clones of this dataset, is this normal? 

@yarik answers "no" and has asked OP to check `.datalad/config`

Origin: Matrix datalad-channel, 2023-05-11 at 00:58 CES

TODO (not necessarily to be performed in this order)
- [x] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [ ] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by loj** [comment]
The OP's problem was solved by modifying the `.datalad/config` to fix the path. However, I think there's still an open question on whether or not `datalad containers-add` is behaving in a sub-optimal way. I've asked OP to provide the `datalad containers-add` call that resulted in an absolute path being used.

**Comment by loj** [comment]
No further information has been provided by OP with regards to the `datalad containers-add` call that resulted in absolute paths. I tried to reproduce this, but was unable to.

The DataLad Handbook has a chapter on [datalad-containers](https://handbook.datalad.org/en/latest/basics/101-133-containersrun.html#using-datalad-containers), and has a special section on how `.datalad/config`  is modified by `datalad containers-add`. I think this covers the situation sufficiently, so I will close this. If we get more information or another report of this happening, this can be reopened.
