### ISSUE TITLE
Should we add a KBI on converting a subdirectory into a subdataset?

### ISSUE THREAD

**Issue by christian-monch** [psychoinformatics-de/knowledge-base#68]
During support shifts the question "how do I convert a sub-directory" into a sub-dataset was raised. The question was answered and the support issue (https://github.com/psychoinformatics-de/knowledge-base/issues/63) was closed.  Nevertheless, no KBI was created yet.

There is a discussion in the support issue (https://github.com/psychoinformatics-de/knowledge-base/issues/63#issuecomment-1541470857) about whether a more detailed answer to the question should be written into a KBI.

**Comment by mih** [comment]
I think the original assessment by @mslw is valid. We have quite a few materials already. A KBI would either repeat a lot or be those references. I think for now it is not needed. Helpful, but not needed.
