### ISSUE TITLE
Permanently unlocking files; running standalone software with `datalad run`

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/knowledge-base#76]
Origin: Datalad Matrix chat

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [x] Inform OP about resolution

Issue is resolved, but a good KBI candidate:

> Dear Datalad team, I had my first bad experience with datalad today and wondered if this could be improved. This is what happened: I was using a standard software of my field to process a batch of my data. The software has a beautiful and very useful user interface that helps to refine signal selection, and it automatically saves away the changes one makes in the background in a python .npy file, online. I spent half a day working away on my data and closed the program when I was done as what I am used to do. Just to realized that no changes were saved because I did not unlock the .npy file before I started working. All progress lost. When I checked the console output later I do see the PermissionError showing up there, but since it didn't make to the foreground I did not notice it before it was too late. Why do files always have to be locked by default? This is very inconvenient for my case. I wonder if I could have them in a permenant unlocked state.

Sorry to hear that. Yes, it is possible to make files permanently unlocked. Take a look here: https://git-annex.branchable.com/tips/unlocked_files/

Make sure to read that entire page. While it may help you in this particular case, it could hurt you in another.

My personal recommendation would be to use datalad run, not unlocking files.

That being said, if that signal selection software piece does not alert you when it is unable to save a file, this is also worth a bug report.

> I just tried out running the software with `datalad run suite2p` and was surprised that it actually works 😲 (I had doubts because it is a standalone software with a gui and I just assumed it wouldn't work the same way as running a script). When supplied with `-o myfile.npy` it was actually doing its magic: allowed me to use the software the usual way and suite2p to save the changes as intended in the background. Upon closing the program, the whole operation is logged with a datalad run commit. 👌👏 So far it looks like I can well integrate this into my workflow 🤸‍♀️🤹‍♀️ Hub ab!
> Is there a way to pass an expression to the -o  so it will unlock all files called iscell.npy in all subdirectories?

Yes, check the --help. Here is a snippet:

```
Use ** to match any file at any directory depth recursively. Single *
does not check files within matched directories.::

   % datalad run -m 'run my script' -i 'data/**/*.dat' \
     -o 'output_dir/**' 'code/script.sh'
```

**Comment by jsheunis** [comment]
I've gone through this issue again, and actually everything related to `datalad run` and the locking and unlocking of annexed files is covered extensively in the handbook, e.g.: https://handbook.datalad.org/en/latest/basics/101-114-txt2git.html#data-safety

So I would say the only aspect in this issue that could be considered new/unique is the example of running standalone software through `datalad run`. I am unsure about whether this should be a KBI. If so, something like "Can I run standalone/GUI software reproducibly with `datalad run`"?

**Comment by loj** [comment]
> So I would say the only aspect in this issue that could be considered new/unique is the example of running standalone software through datalad run. I am unsure about whether this should be a KBI. 

Rather than a KBI, maybe a better fit for this would be adding a short note in the handbook chapter on `datalad run`. WDYT?

**Comment by adswa** [comment]
I'm linking this existing KBI here, too, which demonstrates this for the jupyter tool: https://knowledge-base.psychoinformatics.de/kbi/0003/index.html. I'm fine with creating a snippet in the handbook, too, I was surprised to find one already :+1:. Maybe in the course of Julien Coloumbs PR.

**Comment by loj** [comment]
Aaah, right! I forgot about that KBI. Personally I think that with this KBI and the upcoming Handbook PR it is sufficiently covered, so I will close this. But feel free to reopen if you disagree.
